
# mysql
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.13:3306/mall-wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  # nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-ware
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 11001