
# mysql
spring:
  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.13:3306/mall-pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
# mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
server:
  port: 10001